### ISSUE TITLE
bin/console jobsbymail cleanup does not work any more

### ISSUE THREAD

**Issue by cbleek** [yawik/JobsByMail#3]
It's probably because the ZF3 upgrade. The command gives an exception

@fedys can you take a look?

```
root@yawik:/var/www/yawik.org# bin/console jobsbymail cleanup
======================================================================
   The application has thrown an exception!
======================================================================
 Zend\ServiceManager\Exception\ServiceNotFoundException
 Unable to resolve service "ErrorLogger" to a factory; are you certain you provided it during configuration?
----------------------------------------------------------------------
/var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:681
#0 /var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(757): Zend\ServiceManager\ServiceManager->getFactory('ErrorLogger')
#1 /var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate('ErrorLogger')
#2 /var/www/yawik.org/module/JobsByMail/src/JobsByMail/Factory/Service/MailerFactory.php(32): Zend\ServiceManager\ServiceManager->get('ErrorLogger')
#3 /var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(758): JobsByMail\Factory\Service\MailerFactory->__invoke(Object(Zend\ServiceManager\ServiceManager), 'JobsByMail\\Serv...', NULL)
#4 /var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate('JobsByMail\\Serv...')
#5 /var/www/yawik.org/module/JobsByMail/src/JobsByMail/Factory/Controller/ConsoleControllerFactory.php(30): Zend\ServiceManager\ServiceManager->get('JobsByMail\\Serv...')
#6 /var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(758): JobsByMail\Factory\Controller\ConsoleControllerFactory->__invoke(Object(Zend\ServiceManager\ServiceManager), 'JobsByMail/Cons...', NULL)
#7 /var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate('JobsByMail/Cons...')
#8 /var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(141): Zend\ServiceManager\ServiceManager->get('JobsByMail/Cons...')
#9 /var/www/yawik.org/vendor/zendframework/zend-mvc/src/DispatchListener.php(95): Zend\ServiceManager\AbstractPluginManager->get('JobsByMail/Cons...')
#10 /var/www/yawik.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 /var/www/yawik.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /var/www/yawik.org/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#13 /var/www/yawik.org/public/index.php(50): Zend\Mvc\Application->run()
#14 /var/www/yawik.org/bin/console(2): include('/var/www/yawik....')
#15 {main}
======================================================================
   Previous Exception(s):

```

**Comment by fedys** [comment]
Yes, I can take a look at it this weekend. It is a tiny issue.

**Comment by fedys** [comment]
Done in https://github.com/yawik/JobsByMail/commit/456f62346c4307ed91768b59e34238d827961be3

**Comment by fedys** [comment]
I have also fixed PHPUnit tests in https://github.com/yawik/JobsByMail/commit/9096c0307d6074b1994dcdfe3b23fe5d9e7e21b7

**Comment by fedys** [comment]
I noticed a minor issue related to uploading code coverage in the [Travis build](https://travis-ci.org/yawik/JobsByMail/builds/284578186) 

```shell
$ php ocular.phar code-coverage:upload --format=php-clover test/build/logs/clover.serialized
#!/usr/bin/env php
Uploading code coverage for repository "g/yawik/JobsByMail" and revision "9096c0307d6074b1994dcdfe3b23fe5d9e7e21b7"... Failed
{"error":{"code":404,"message":"Not Found"}}
```

I have no idea how to fix that.

**Comment by cbleek** [comment]
the module is working again.

I don't understand the problem with the coverage upload. 

https://coveralls.io/github/yawik/JobsByMail?branch=develop

it seems, that coveralls.io was updated. I've created #4
