### ISSUE TITLE
Confirming a search profile leads to an error

### ISSUE THREAD

**Issue by cbleek** [yawik/JobsByMail#5]
By clicking the confirmation link in the email, an error occurs

![auswahl_999 572](https://user-images.githubusercontent.com/858642/31832465-6b7dce50-b5c7-11e7-97a2-db9aeba243b2.png)

This has propably something to do with the ZF3 Upgrade. @fedys can you take a look?

```
An error occurred
An error occurred during execution; please try again later.
Additional information:
Zend\ServiceManager\Exception\ServiceNotFoundException
File:
/var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:681
Message:
Unable to resolve service "Translator" to a factory; are you certain you provided it during configuration?
Stack trace:
#0 /var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(757): Zend\ServiceManager\ServiceManager->getFactory('Translator')
#1 /var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate('Translator')
#2 /var/www/yawik.org/module/JobsByMail/src/JobsByMail/Factory/Controller/ConfirmControllerFactory.php(32): Zend\ServiceManager\ServiceManager->get('Translator')
#3 /var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(758): JobsByMail\Factory\Controller\ConfirmControllerFactory->__invoke(Object(Zend\ServiceManager\ServiceManager), 'JobsByMail/Conf...', NULL)
#4 /var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate('JobsByMail/Conf...')
#5 /var/www/yawik.org/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(141): Zend\ServiceManager\ServiceManager->get('JobsByMail/Conf...')
#6 /var/www/yawik.org/vendor/zendframework/zend-mvc/src/DispatchListener.php(95): Zend\ServiceManager\AbstractPluginManager->get('JobsByMail/Conf...')
#7 /var/www/yawik.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /var/www/yawik.org/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /var/www/yawik.org/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#10 /var/www/yawik.org/public/index.php(50): Zend\Mvc\Application->run()
#11 {main}
```

**Comment by fedys** [comment]
I can take a look at it on Thursday.

**Comment by fedys** [comment]
Fixed in https://github.com/yawik/JobsByMail/commit/9aaae4a380959694076d305750d8be88d7fd7709

**Comment by cbleek** [comment]
works. thanks!
